// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opieiqckcfjbbwelomzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9waWVpcWNrY2ZqYmJ3ZWxvbXpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NjQ4MTksImV4cCI6MjA2ODA0MDgxOX0.KNUhfZzPFHLwD5dbRYv2snQLKVmdBndyWF3sXx1tQDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});